[book]
authors = ["Ballad"]
language = "zh-CN"
multilingual = false
src = "src"
title = "Ballad's workspace"

[output.html]
default-theme = "rust"
preferred-dark-theme = "rust"
git-repository-url = "https://github.com/junjielu/Workspace"
git-repository-icon = "fa-github"

[output.html.fold]
enable = false
level = 0

[output.html.search]
limit-results = 15